### ISSUE TITLE
User can view posts

### ISSUE THREAD

**Issue by dione-dls** [ZoeKavanagh/fishnet#3]
AS A user
I WANT to view posts
SO THAT I can see what my friends are doing

- user is in '/posts'
- user will see top 10 posts by date ( posts contain name, timestamp, and post in text format)

**Comment by benfurber** [comment]
Documenting work: https://github.com/ZoeKavanagh/fishnet/wiki/Posts

**Comment by benfurber** [comment]
Work done, just need to update documentation now.
